# Generated by Django 6.0.5 on 2026-05-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Sinf raqami (7, 8, 9, 10, 11)', null=True),
        ),
    ]
