# Generated by Django 6.0.5 on 2026-05-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FizikBirlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(help_text='Masalan: Nyuton, Joul, Vatt', max_length=255, verbose_name='Nomi')),
                ('belgi', models.CharField(help_text='Masalan: N, J, W', max_length=50, verbose_name='Belgisi')),
                ('sistema', models.CharField(choices=[('SI', 'SI (Xalqaro sistema)'), ('CGS', 'CGS'), ('boshqa', 'Boshqa')], default='SI', max_length=10, verbose_name="O'lchov sistemasi")),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_published', models.BooleanField(default=True, verbose_name='Nashr etilgan')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Fizik birlik',
                'verbose_name_plural': 'Fizik birliklar',
                'ordering': ['sistema', 'order', 'nomi'],
            },
        ),
        migrations.CreateModel(
            name='FizikKattaik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255, verbose_name='Nomi')),
                ('belgi', models.CharField(help_text='Masalan: F, m, v, a', max_length=50, verbose_name='Belgisi')),
                ('olchov_birligi', models.CharField(help_text='Masalan: N, kg, m/s, m/s²', max_length=100, verbose_name="O'lchov birligi")),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_published', models.BooleanField(default=True, verbose_name='Nashr etilgan')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Fizik kattaik',
                'verbose_name_plural': 'Fizik kattaliklar',
                'ordering': ['order', 'nomi'],
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('formula', models.CharField(help_text='Masalan: F = ma, T = 2π√(L/g)', max_length=255, verbose_name='Formula')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('kategoriya', models.CharField(choices=[('mexanika', 'Mexanika'), ('elektr', 'Elektr va magnit'), ('optika', 'Optika'), ('termodinamika', 'Termodinamika'), ('kvant', 'Kvant fizikasi'), ('boshqa', 'Boshqa')], default='mexanika', max_length=20, verbose_name='Kategoriya')),
                ('image', models.ImageField(blank=True, null=True, upload_to='formulalar/', verbose_name='Rasm')),
                ('is_published', models.BooleanField(default=True, verbose_name='Nashr etilgan')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Formula',
                'verbose_name_plural': 'Formulalar',
                'ordering': ['order', 'title'],
            },
        ),
    ]
