# Generated by Django 6.0.5 on 2026-05-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referenslar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FizikBirlikCGS',
            fields=[
            ],
            options={
                'verbose_name': 'CGS birligi',
                'verbose_name_plural': 'CGS birliklari',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('referenslar.fizikbirlik',),
        ),
        migrations.CreateModel(
            name='FizikBirlikSI',
            fields=[
            ],
            options={
                'verbose_name': 'SI birligi',
                'verbose_name_plural': 'SI birliklari',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('referenslar.fizikbirlik',),
        ),
        migrations.CreateModel(
            name='FormulaElektr',
            fields=[
            ],
            options={
                'verbose_name': 'Elektr formulasi',
                'verbose_name_plural': 'Elektr va magnit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('referenslar.formula',),
        ),
        migrations.CreateModel(
            name='FormulaKvant',
            fields=[
            ],
            options={
                'verbose_name': 'Kvant formulasi',
                'verbose_name_plural': 'Kvant fizikasi',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('referenslar.formula',),
        ),
        migrations.CreateModel(
            name='FormulaMexanika',
            fields=[
            ],
            options={
                'verbose_name': 'Mexanika formulasi',
                'verbose_name_plural': 'Mexanika',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('referenslar.formula',),
        ),
        migrations.CreateModel(
            name='FormulaOptika',
            fields=[
            ],
            options={
                'verbose_name': 'Optika formulasi',
                'verbose_name_plural': 'Optika',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('referenslar.formula',),
        ),
        migrations.CreateModel(
            name='FormulaTermodinamika',
            fields=[
            ],
            options={
                'verbose_name': 'Termodinamika formulasi',
                'verbose_name_plural': 'Termodinamika',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('referenslar.formula',),
        ),
    ]
