export interface DailyItem  { icon: string; name: string; desc: string }
export interface FieldItem  { icon: string; field: string; desc: string }
export interface Formula    { expr: string; desc: string }

export interface SimInfo {
  title: string
  subtitle: string
  year: string
  discoverer: string
  country: string
  historyStory: string
  historyDev: string[]
  whatSimple: string
  whatScientific: string
  formulas: Formula[]
  visual: string
  daily: DailyItem[]
  fields: FieldItem[]
  whyText: string
  withoutIt: string
  future: string
  facts: string[]
  homeExp: string
  labExp: string
  safety: string
}

export const SIM_INFO: Record<string, SimInfo> = {

  pendulum: {
    title: "Matematik mayatnik",
    subtitle: "Davriy harakat va uzunlik munosabati",
    year: "1602",
    discoverer: "Galileo Galilei",
    country: "Italiya",
    historyStory: "1602-yilda Galileo Galilei Piza katedralida katta shamdonning tebranishini kuzatib, pulsini soat sifatida ishlatdi. Hayratlanarli kashfiyot: burchak qanchalik bo'lishidan qat'iy nazar, tebranish davri bir xil! Keyinroq davr faqat ipning uzunligiga bog'liq ekanligini matematika orqali isbotladi.",
    historyDev: [
      "1656 — Xuygens birinchi pendulum soatini ixtiro qildi, navigatsiyani inqilobga olib keldi",
      "1851 — Foucault 67 metrli mayatnik bilan Yerning o'z o'qi atrofida aylanishini isbotladi",
      "1930-yillar — Kvant mexanikasi mayatnikni yangi darajada tushuntira boshladi",
      "Hozir — LIGO gravitatsion to'lqin detektori ulkan mayatnik printsipi asosida ishlaydi",
    ],
    whatSimple: "Tasavvur qiling: ipga bog'langan og'irlik. Uni bir tomonga tortib qo'ying — u oldinma-orqaga tebranadi. Uzun ip → sekin tebranish, qisqa ip → tez tebranish. Og'irlik muhim emas! 100 gramm ham, 1 kilo ham bir xil tebranadi.",
    whatScientific: "Matematik mayatnik — tayanch nuqtasidan osilgan og'irligi e'tiborsiz ipdagi nuqtaviy massaning erkin tebranishi. Kichik burchaklarda (15° gacha) T = 2π√(L/g) formulasiga bo'ysunadi.",
    formulas: [
      { expr: "T = 2π√(L/g)", desc: "Davr (T — sekund, L — uzunlik metr, g = 9.8 m/s²)" },
      { expr: "ω = √(g/L)", desc: "Burchak chastotasi (rad/s)" },
      { expr: "E = mgl(1 - cosθ)", desc: "Potensial energiya" },
    ],
    visual: "⬆️ Tayanch\n   |\n   | (ip L)\n   |\n  🔵 (bob)\n  ↙️ ↘️ tebranish",
    daily: [
      { icon: "⏰", name: "Pendulum soat", desc: "Xuygens 1656-da ixtiro qilgan. 400 yil davomida eng aniq vaqt o'lchov vositasi" },
      { icon: "🎵", name: "Metronom", desc: "Musiqachilar uchun ritm o'lchagich — mayatnik printsipi asosida ishlaydi" },
      { icon: "🌍", name: "Seysmograf", desc: "Zilzila to'lqinlarini mayatnik tebranishlari orqali qayd etadi" },
      { icon: "🏗️", name: "Qurilish plumb bob", desc: "Vertikal o'lchov uchun — ipga osilgan og'irlik vertikal chiziqni ko'rsatadi" },
      { icon: "🏚", name: "Ko'ngilochar atraksionlar", desc: "Salqin tebranuvchan o'rindiqlar mayatnik harakati asosida" },
      { icon: "🔬", name: "Gravimetr", desc: "Yer tortishi kuchlanishining o'zgarishini o'lchaydi — neft topishda ishlatiladi" },
    ],
    fields: [
      { icon: "⏱️", field: "Soatchilik", desc: "Pendulum soatlar 300 yil davomida standart vaqt o'lchov vositasi bo'lgan" },
      { icon: "🚢", field: "Navigatsiya", desc: "Dengiz sayohatlari uchun aniq vaqt o'lchash — koordinatalarni aniqlash imkonini berdi" },
      { icon: "🌍", field: "Geofizika", desc: "Gravimetrlar Yer ichki tuzilmasini o'rganadi, neft va foydali qazilmalarni topadi" },
      { icon: "🔬", field: "Ilmiy o'lchov", desc: "g — erkin tushish tezlanishi — mayatnik orqali juda aniq o'lchangan" },
    ],
    whyText: "Mayatnik Galileoning zamonaviy ilmiy metodini — kuzatish, gipoteza, tajriba — amalda namoyish etgan birinchi hodisadir. Xuygens ixtirosi tufayli soatchilik sanoati tug'ildi.",
    withoutIt: "Aniq vaqt o'lchashsiz dengiz navigatsiyasi imkonsiz bo'lar edi — kemalar yo'lini yo'qotib, yuzlab fojialar sodir bo'lar edi.",
    future: "Optik soatlar mayatnik prinsipi asosidagi yangi avlod. LIGO detektori — kosmik mayatnik — gravitatsion to'lqinlarni aniqlaydi.",
    facts: [
      "Galileo pulsini soat sifatida ishlatib, davrni o'lchagan",
      "Foucault mayatniki (Paris, 67 m) Yerning aylanishini ko'rsatib, hamma hayratda qoldirdi",
      "Eng uzun mayatnik — 98 metr (AQSh, San-Fransisko)",
      "Massasi davrga ta'sir qilmaydi — bu Galileoning katta kashfiyoti",
      "Oy'da g = 1.62 m/s², shuning uchun mayatnik Yerdan 2.5 marta sekin tebranadi",
    ],
    homeExp: "Ip va turli og'irliklar bilan mayatnik yarating. Ipning uzunligini o'zgartirib, 10 marta tebranish vaqtini o'lchang. Natija: uzunlik 4 barobar oshsa, davr 2 marta oshadi.",
    labExp: "L ni 10 sm dan 100 sm gacha 10 sm qadam bilan o'zgartirib, T ni o'lchang. T² va L orasidagi grafikni chizing — to'g'ri chiziq hosil bo'ladi. Egizgich orqali g ni hisoblang.",
    safety: "Og'irlikni mustahkam bog'lang. Katta burchaklarda tebranish xavfli — 30° dan oshirmang. Atrofda bo'sh joy bo'lsin.",
  },

  "free-fall": {
    title: "Erkin tushish",
    subtitle: "Tortishish kuchi va tezlanish",
    year: "1589",
    discoverer: "Galileo Galilei",
    country: "Italiya",
    historyStory: "Aristotel 2000 yil davomida og'irroq jism tezroq tushadi deb ta'lim berdi. 1589-yilda Galileo Piza minorasidan turli massali sharlarni tashlab, ularning bir vaqtda yerga tushishini ko'rsatdi va bu katta nazariyani ag'darib tashladi.",
    historyDev: [
      "1604 — Galileo s = 1/2*g*t² formulasini tajribalar orqali tasdiqladi",
      "1687 — Newton universal tortishish qonunini kashf etib, erkin tushishni umumiy qonun bilan birlashtirdi",
      "1971 — Oy'da Apollo 15 astronavti bolg'a va patni bir vaqtda tushirib, Galileoni isbotladi",
    ],
    whatSimple: "Havo bo'lmasa, og'ir tosh ham, yengil pat ham bir xil tezlanadi! Faqat havo qarshiligi farq qilishiga olib keladi. Bu Galileoning buyuk kashfiyoti.",
    whatScientific: "Havo qarshiligi yo'q holda barcha jismlar g = 9.8 m/s² tezlanish bilan tushadi. h = 1/2*g*t², v = g*t.",
    formulas: [
      { expr: "h = ½gt²", desc: "Tushish balandligi (h — metr, g = 9.8, t — sekund)" },
      { expr: "v = gt", desc: "Tushish tezligi" },
      { expr: "v² = 2gh", desc: "Energiya saqlanishi orqali" },
    ],
    visual: "h\n⬇️ g = 9.8 m/s²\n🟤 og'ir\n🍂 yengil\n━━━ yer",
    daily: [
      { icon: "🏄", name: "Suvga sho'ng'ish", desc: "Balandlikdan suvga tushish tezligi g tufayli hisoblashadi" },
      { icon: "✈️", name: "Parashyut", desc: "Havo qarshiligi g ni muvozanatlashtiradi — terminal tezlik" },
      { icon: "⚽", name: "Sport", desc: "To'p uchishi, sakrash — erkin tushish qonunlari asos" },
      { icon: "🚀", name: "Raketa", desc: "Koinotga uchish uchun g ni yengib o'tish kerak — 11.2 km/s" },
      { icon: "🏗️", name: "Qurilish xavfsizligi", desc: "Tushayotgan ob'ekt tezligini hisoblash uchun" },
    ],
    fields: [
      { icon: "🚀", field: "Kosmosnavigatika", desc: "Orbital mexanika — sayyora tortishi va erkin tushish" },
      { icon: "🏥", field: "Tibbiyot", desc: "Yiqilish tezligi va jarohat kuchini hisoblash" },
      { icon: "⚽", field: "Sport fani", desc: "Sakrash, uloqtirish, to'p traektoriyasi" },
    ],
    whyText: "Galileoning erkin tushish kashfiyoti kuzatish va tajribaga asoslangan ilmiy metodning g'alabasini ko'rsatdi. Newton uchun bu universal tortishish qonuniga asos bo'ldi.",
    withoutIt: "Raketa texnologiyasi, kosmosga parvoz, bino qurilishi ham ancha murakkab bo'lar edi.",
    future: "Gravitatsion to'lqin deteksiyasi, kvant gravitatsiya tadqiqotlari.",
    facts: [
      "Oy'da g = 1.62 m/s² — 6 marta kuchsiz",
      "Terminal tezlik odam uchun ~53 m/s (havo qarshiligi bilan)",
      "200 m balandlikdan tushish taxminan 6 sekund",
    ],
    homeExp: "Bir xil balandlikdan bir vaqtda qog'oz va tanga tashlang. Tanga tezroq tushadi (havo qarshiligi). Endi qog'ozni to'p qilib junjikang — ular deyarli bir vaqtda tushadi!",
    labExp: "Fotogate yordamida tushish vaqtini o'lchab, g ni hisoblang. Turli balandliklardan tajriba qilib, h-t² grafigini chizing.",
    safety: "Og'ir narsalarni pastdan kelayotgan odamlar bo'lmaganida tashlang. Shisha narsalar ishlatmang.",
  },

  rotation: {
    title: "Aylanma harakat",
    subtitle: "Moment va burchak tezlanish",
    year: "1687",
    discoverer: "Isaac Newton / Leonhard Euler",
    country: "Angliya / Shveytsariya",
    historyStory: "1687-yilda Newton Principia Mathematica asarida aylanma harakat qonunlarini to'liq tushuntirdi. 1765-yilda Euler burchak impuls va moment tenzori nazariyasini rivojlantirdi.",
    historyDev: [
      "1687 — Newton aylanma harakat uchun F = ma analogini yaratdi",
      "1765 — Euler qattiq jism dinamikasining to'liq nazariyasini berdi",
      "1900s — Gyroscop navigatsiya va aviatsiyada qo'llanila boshladi",
    ],
    whatSimple: "Jism o'z o'qi atrofida aylanadi. Muzda figurali uchuvchi qo'llarini yig'sa tezlashadi — burchak impulsi saqlanadi! Og'ir va katta jismni aylantirish qiyinroq.",
    whatScientific: "I*α = τ (inersiya momenti x burchak tezlanish = kuch momenti). L = I*ω — burchak impulsi saqlanadi.",
    formulas: [
      { expr: "τ = Iα", desc: "Kuch momenti (Nm) = inersiya momenti × burchak tezlanish" },
      { expr: "L = Iω", desc: "Burchak impulsi (saqlanish qonuni)" },
      { expr: "E = ½Iω²", desc: "Aylanma kinetik energiya" },
    ],
    visual: "    ↺ ω\n  ←⊙→\n    ↻\n  Iα = τ",
    daily: [
      { icon: "🌍", name: "Yer aylanishi", desc: "24 soatda bir to'liq aylanish — kun va tun" },
      { icon: "🚗", name: "Avtomobil g'ildiraklari", desc: "Torque — dvigatel burilish kuchi" },
      { icon: "🎡", name: "Ferris g'ildirak", desc: "Katta inersiya momenti — sekin to'xtaydi" },
      { icon: "🏂", name: "Figurali uchish", desc: "Qo'llarni yig'sa tezlashadi (L = const)" },
      { icon: "🔄", name: "Gyroscop", desc: "Samolyot va kemalarni yo'naltirishda ishlatiladi" },
    ],
    fields: [
      { icon: "✈️", field: "Aviatsiya", desc: "Gyroscop va navigatsiya tizimlari" },
      { icon: "⚙️", field: "Mashinasozlik", desc: "Dvigatel, turbina, g'ildirak dizayni" },
      { icon: "🚀", field: "Kosmosnavigatika", desc: "Sun'iy yo'ldosh orientatsiyasi" },
    ],
    whyText: "Aylanma harakat qonunlari zamonaviy mashinasozlikning asosi — dvigateldan turbinagacha.",
    withoutIt: "Zamonaviy transport va navigatsiya texnologiyasi mavjud bo'lmas edi.",
    future: "Kvant spintronica — elektronning spin xossalaridan foydalanish.",
    facts: [
      "Yer o'qi atrofida aylanishi sekinlashmoqda — har 100 yilda 0.002 sekund",
      "Neytron yulduzlar sekundiga 700 marta aylanadi",
    ],
    homeExp: "Stulda o'tirib, og'irlik ushlab, qo'llarni yoyib aylaning — so'ng yig'ing va tezlashganingizni his eting.",
    labExp: "Turli radius va massadagi disklarning inersiya momentlarini tajriba qilib hisoblang.",
    safety: "Aylanayotgan jismlarga qo'l tegizmang. Kiyimlar va sochlar uralash xavfi bor.",
  },

  collision: {
    title: "To'qnashuv (elastik/noelastik)",
    subtitle: "Impuls va energiya saqlanishi",
    year: "1669",
    discoverer: "John Wallis, Christiaan Huygens, Christopher Wren",
    country: "Angliya / Niderlandiya",
    historyStory: "1669-yilda Royal Society musobaqasida uch olim — Wallis, Huygens va Wren — mustaqil ravishda to'qnashuv qonunlarini taqdim etdilar. Huygens elastik to'qnashuv uchun to'liq nazariya yaratdi.",
    historyDev: [
      "1687 — Newton impuls saqlanish qonunini umumiy shaklda berdi",
      "1880s — Zarralar fizikasida to'qnashuv o'rganila boshladi",
      "2012 — LHC da protonlar to'qnashtirilib, Higgs bozoni kashf etildi",
    ],
    whatSimple: "Ikki narsa to'qnashganda ular bir-biriga ta'sir qiladi. Elastik — hamma narsa qaytib ketadi (bilyard). Noelastik — birlashib ketadi (qor to'pi).",
    whatScientific: "To'qnashuvda umumiy impuls saqlanadi: m₁v₁ + m₂v₂ = m₁v₁' + m₂v₂'. Elastikda kinetik energiya ham saqlanadi.",
    formulas: [
      { expr: "m₁v₁ + m₂v₂ = const", desc: "Impuls saqlanishi" },
      { expr: "e = (v₂' - v₁') / (v₁ - v₂)", desc: "Restitusiya koeffitsienti (0 = noelastik, 1 = elastik)" },
    ],
    visual: "🔵→  ←🔴\nTo'qnashuv\n←🔵  🔴→",
    daily: [
      { icon: "🎱", name: "Bilyard", desc: "Deyarli elastik to'qnashuv — sharlar impulsi almashadi" },
      { icon: "🚗", name: "Avtomobil xavfsizligi", desc: "Deformatsiyalanadigan zona — noelastik to'qnashuv energiyani yutadi" },
      { icon: "⚽", name: "Sport to'plari", desc: "To'p va joy to'qnashuvi" },
    ],
    fields: [
      { icon: "🔬", field: "Zarralar fizikasi", desc: "LHC da protonlar to'qnashtirilib yangi zarralar topiladi" },
      { icon: "🚗", field: "Avtomobil sanoati", desc: "Baxtsizlik xavfsizligi dizayni" },
    ],
    whyText: "Impuls saqlanish qonuni zamonaviy zarrachalar fizikasining asosi — Higgs bozoni shu orqali aniqlangan.",
    withoutIt: "Zamonaviy zarrachalar fizikasi va atom energiyasi texnologiyasi rivojlanmas edi.",
    future: "Kvant to'qnashuvlar, kvant xatoliklarni tuzatish.",
    facts: [
      "LHC da protonlar yorug'lik tezligining 99.9999% da to'qnashadi",
      "Avtomobil baxtsizligida qora quti to'qnashuv ma'lumotlarini saqlaydi",
    ],
    homeExp: "Ikkita o'xshash to'p birini ikkinchisiga turtib ko'ring — impuls uzatilishini kuzating.",
    labExp: "Havo yostiqchasida turli massali aravchalardagi to'qnashuvlarni o'lchab, impuls saqlanishini tasdiqlang.",
    safety: "Kuchli to'qnashuvlarda himoya ko'zoynak kiyish tavsiya etiladi.",
  },

  gravity: {
    title: "Og'irlik kuchi",
    subtitle: "Universal tortishish qonuni",
    year: "1687",
    discoverer: "Isaac Newton",
    country: "Angliya",
    historyStory: "Rivoyatga ko'ra, 1687-yilda Newton bog'da o'tirganida olma tushdi va u 'Nega olma Oyga emas, Yerga tushadi?' degan savolni berdi. Bu savol uni universal tortishish qonuniga olib keldi.",
    historyDev: [
      "1687 — Principia Mathematica da F = Gm₁m₂/r² chop etildi",
      "1798 — Cavendish G konstantasini laboratoriyada o'lchadi",
      "1915 — Einstein umumiy nisbiylik nazariyasida tortishishni fazovaqt egriligi sifatida talqin etdi",
    ],
    whatSimple: "Barcha jismlar bir-birini tortadi! Qanchalik og'ir — shunchalik kuchli tortadi. Qanchalik uzoq — shunchalik zaif. Siz ham Oyni tortasiz, lekin Oy juda og'ir.",
    whatScientific: "F = Gm₁m₂/r² — ikki jism orasidagi tortishish kuchi massalar ko'paytmasiga to'g'ri, masofa kvadratiga teskari proporsional.",
    formulas: [
      { expr: "F = Gm₁m₂/r²", desc: "Universal tortishish (G = 6.674×10⁻¹¹ Nm²/kg²)" },
      { expr: "g = GM/R²", desc: "Sayyora sirtidagi erkin tushish tezlanishi" },
      { expr: "v = √(GM/r)", desc: "Orbital tezlik" },
    ],
    visual: "🌍\n↕️ F\n🍎\n\nF = Gm₁m₂/r²",
    daily: [
      { icon: "🌊", name: "Suv to'lqinlari", desc: "Oy va Quyosh Yer okeanlarini tortib, ko'tarilishlarni hosil qiladi" },
      { icon: "🚀", name: "Kosmik kemalar", desc: "Sayyora orbitasi va parvoz yo'nalishlari" },
      { icon: "⚽", name: "Sport", desc: "To'p traektoriyasi, sakrash masofasi" },
      { icon: "☀️", name: "Quyosh tizimi", desc: "Sayyoralar orbitada bo'lishining sababi" },
    ],
    fields: [
      { icon: "🚀", field: "Kosmosnavigatika", desc: "Orbital mexanika, yo'ldosh uchirilishi" },
      { icon: "🌍", field: "Geofizika", desc: "Yer ichki tuzilmasi, zilzila zonalari" },
      { icon: "⚡", field: "Energetika", desc: "Suv to'g'onlari — potensial energiya" },
    ],
    whyText: "Newton qonuni astronomiyani, navigatsiyani va zamonaviy kosmosni tutib turadi. GPS satellit tizimlari shu qonunga asoslanadi.",
    withoutIt: "Kosmosga parvoz, sun'iy yo'ldoshlar, GPS — hamma narsa imkonsiz bo'lar edi.",
    future: "Kvant gravitatsiya — eng katta hal qilinmagan muammo. Gravitatsion to'lqin astronomiyasi.",
    facts: [
      "Oy'da og'irligingiz 6 marta kamayadi",
      "Qora qo'ylarda tortishish shunchalik kuchli — yorug'lik ham chiqolmaydi",
      "GPS satellit soatlari gravitatsion vaqt cho'zilishi tufayli tuzatish talab qiladi",
    ],
    homeExp: "Balandroq joydan suvni tomizib, parabolik traektoriyani kuzating.",
    labExp: "Kavendish torsion balansasi yordamida G ni o'lching.",
    safety: "Balandlikdan tajriba qilganda, pastda hech kim bo'lmasin.",
  },

  harmonic: {
    title: "Garmonik tebranish",
    subtitle: "Prujina va sinusoidal harakat",
    year: "1678",
    discoverer: "Robert Hooke",
    country: "Angliya",
    historyStory: "1678-yilda Robert Hooke 'Ut tensio, sic vis' (qanchalik cho'zilsa, shunchalik kuch) degan qonunni kashf etdi. Bu elastik kuchning deformatsiyaga proporsionalligini ifodalaydi va garmonik tebranishning asosi.",
    historyDev: [
      "1678 — Hooke qonuni: F = -kx",
      "1700s — Euler va Lagrange garmonik tebranishning matematik nazariyasini yaratdi",
      "1900s — Kvant garmonik oscillator — kvant mexanikasining eng muhim modeli",
    ],
    whatSimple: "Prujinaga osilgan og'irlikni tortib qo'ysangiz, u ilgari-keyin tebranadi. Tebranish sinusoidal — grafikda chiroyli to'lqin shakl hosil bo'ladi.",
    whatScientific: "Tiklaydi kuch F = -kx bo'lganda, harakat x = A*cos(ωt + φ) qonuniga bo'ysunadi. ω = √(k/m).",
    formulas: [
      { expr: "F = -kx", desc: "Hooke qonuni (k — elastiklik koeffitsienti)" },
      { expr: "T = 2π√(m/k)", desc: "Tebranish davri" },
      { expr: "x = A·cos(ωt + φ)", desc: "Koordinata vaqt bo'yicha" },
    ],
    visual: "━━━ tayanch\n   🌀 (prujina)\n   🔵 (massa)\n↕️ tebranish",
    daily: [
      { icon: "🎻", name: "Torli musiqa asboblari", desc: "Tor garmonik oscillator, undan notalar hosil bo'ladi" },
      { icon: "🔔", name: "Qo'ng'iroq", desc: "Elastik tebranish — eshitilgan tovush" },
      { icon: "❤️", name: "Yurak urishi", desc: "Yurak muskulining ritmik qisqarishi" },
      { icon: "🌉", name: "Ko'prik tebranishi", desc: "Rezonans tufayli ko'prik qulab ketishi mumkin (Tacoma)" },
      { icon: "🚗", name: "Amortizator", desc: "Avtomobil yelkani — so'numlangan garmonik oscillator" },
    ],
    fields: [
      { icon: "🎵", field: "Akustika", desc: "Musiqa notalari, ovoz to'lqinlari" },
      { icon: "⚡", field: "Elektronika", desc: "LC zanjirlar — elektr oscillatorlar" },
      { icon: "🔬", field: "Spektroskopiya", desc: "Molekulalarning tebranish chastotalari" },
    ],
    whyText: "Garmonik oscillator — fizikaning eng universal modeli. Kvant mexanikasidan tortib akustikagacha hamma joyda uchraydi.",
    withoutIt: "Musiqa, radio texnologiyasi, kvant kompyuterlar bo'lmas edi.",
    future: "Kvant garmonik oscillatorlar kvant kompyuterlarning qubit-lari asosi.",
    facts: [
      "Kvant garmonik oscillator hech qachon mutlaq tinch turmaydi (zero-point energy)",
      "Tacoma Narrows ko'prigi 1940-yilda rezonans tufayli qulab tushdi",
    ],
    homeExp: "Kauchuk lentasiga tosh bog'lab, vertikal tebrating. T = 2π√(m/k) ni eksperiment orqali tekshiring.",
    labExp: "Turli massalar va prujina konstantalari uchun T ni o'lchab, grafik chizing.",
    safety: "Kuchli prujinalar bilan ehtiyot bo'ling — ular ko'z xavfini tug'dirishi mumkin.",
  },

  electric: {
    title: "Elektr maydon",
    subtitle: "Zaryadlar orasidagi kuch va potensial",
    year: "1785",
    discoverer: "Charles-Augustin de Coulomb",
    country: "Fransiya",
    historyStory: "1785-yilda Sharl Kulon o'zining torsiyon tarozisi yordamida zaryadlangan sharlar orasidagi kuchni o'lchab, Kulon qonunini kashf etdi. Avvalroq 1600-yilda Uilyam Gilbert elektr va magnit hodisalarini birinchi bo'lib sistemali o'rgangan edi.",
    historyDev: [
      "1837 — Faraday elektr maydon tushunchasini kiritdi va maydon chiziqlari g'oyasini taklif etdi",
      "1864 — Maksvell elektr va magnit maydonlarini to'liq matematik nazariyaga birlashtirdi",
      "1905 — Einstein nisbiylik nazariyasida elektr va magnit maydonlar bir xil hodisaning ikki ko'rinishi ekanligini ko'rsatdi",
    ],
    whatSimple: "Zaryadlangan jismlar atrofida ko'rinmas kuch maydoni hosil bo'ladi. Musbat zaryad maydon chizig'ini chiqaradi, manfiy esa yutadi. Xuddi shu kuch sensorli telefoningizni ishlata olish imkonini beradi!",
    whatScientific: "Elektr maydon E = F/q — birlik zaryadga ta'sir etuvchi kuch. Kulon qonuni: F = kq₁q₂/r². Maydon chiziqlari kuchning yo'nalishini ko'rsatadi.",
    formulas: [
      { expr: "F = kq₁q₂/r²", desc: "Kulon kuchi (k = 8.99×10⁹ Nm²/C²)" },
      { expr: "E = F/q = kq/r²", desc: "Elektr maydon kuchlanganligi (N/C)" },
      { expr: "U = kq/r", desc: "Elektr potensial (V)" },
    ],
    visual: "+ ——→——→——→\n     E yo'nalishi\n- ←——←——←——",
    daily: [
      { icon: "📱", name: "Sensorli ekran", desc: "Barmog'ingiz zaryadini sezib, tegish joyini aniqlaydi" },
      { icon: "⚡", name: "Chaqmoq", desc: "Bulut va yer orasidagi kuchli elektr maydon — 300 million volt" },
      { icon: "🖨️", name: "Lazer printer", desc: "Toner zaryadlar orqali qog'ozga aniq yopishtiriladi" },
      { icon: "💉", name: "EKG", desc: "Yurak elektr maydoni tananing sirtida o'lchanadi" },
      { icon: "🚗", name: "Elektr motor", desc: "Elektr maydon kuchi mexanik aylanishga aylanadi" },
      { icon: "🌽", name: "Elektrostatik bo'yash", desc: "Sanoatda metall buyumlar zaryadlanib, bo'yoq jalb qilinadi" },
    ],
    fields: [
      { icon: "🏥", field: "Tibbiyot", desc: "EKG, EEG, defibrillator, MRI — barchasi elektr maydon asosida" },
      { icon: "💻", field: "Elektronika", desc: "Tranzistor, kondensator, integral sxemalar" },
      { icon: "⚡", field: "Elektr energetikasi", desc: "Transformator, generator, elektr uzatish liniyalari" },
      { icon: "🔬", field: "Zarralar fizikasi", desc: "LHC zarrachalar tezlatgichi elektr maydon bilan ishlaydi" },
    ],
    whyText: "Elektr maydon zamonaviy sivilizatsiyaning asosi. Kompyuter, telefon, internet, tibbiy jihozlar — hammasi elektr maydon qonunlariga asoslanadi.",
    withoutIt: "Kompyuter, telefon, televizor, elektr chiroq, tibbiy EKG — bugungi texnologiyaning hech biri bo'lmas edi.",
    future: "Kvant kompyuterlar uchun elektrostatik qubit-lar, nanotexnologiya, kvant elektronika.",
    facts: [
      "Chaqmoq 300 million volt — ammo 0.2 sekund davom etadi",
      "Inson tanasidagi 37 trillion hujayraning har biri kichik elektr maydon yaratadi",
      "Akulalar 0.01 nV/m kuchlilikdagi maydonni his qiladi",
      "Tesla rulotlari million voltdan oshiq hosil qiladi",
      "Yer o'z atmosferasida global elektr zanjirini ushlab turadi",
    ],
    homeExp: "Shisha tayoqni ipak mato bilan ishqalab, mayda qog'oz bo'laklariga yaqinlashtiring. Ular yapishib qoladi — elektrostatik induksiya.",
    labExp: "Van de Graaf generatori va Faraday kletka bilan maydon tasvirini o'rganing. Kulon qonunini torsion balansida tasdiqlang.",
    safety: "Hech qachon yuqori kuchlanishli tizimlarga tegmang. Chaqmoq vaqtida ochiq yerda bo'lmang.",
  },

  capacitor: {
    title: "Kondensator zaryadlanishi",
    subtitle: "Elektr zaryad saqlash va razryadlanish",
    year: "1745",
    discoverer: "Pieter van Musschenbroek (Leyden banki)",
    country: "Niderlandiya",
    historyStory: "1745-yilda Niderlandiya fizigi Musschenbroek shisha idishda suv orqali elektr zaryadini saqlashga muvaffaq bo'ldi. Bu Leyden banki — birinchi kondensator — deb nomlandi.",
    historyDev: [
      "1745 — Leyden banki ixtiro qilindi",
      "1827 — Ohm elektr zanjirlarini o'rganib, RC zanjir nazariyasiga asos soldi",
      "1900s — Zamonaviy kondensatorlar elektronikada ommaviy qo'llanish topdi",
    ],
    whatSimple: "Kondensator — elektr energiyasini vaqtincha saqlaydigan batareya. U tez zaryadlanadi va tez razryadlanadi. Kamera chaqnag'i kondensator energiyasini bir lahzada chiqaradi!",
    whatScientific: "C = Q/V (kapasite = zaryad/kuchlanish). RC zanjirda zaryadlanish: V(t) = V₀(1 - e^(-t/RC)).",
    formulas: [
      { expr: "C = Q/V", desc: "Kapasite (Farad = Kulon/Volt)" },
      { expr: "E = ½CV²", desc: "Saqlangan energiya" },
      { expr: "τ = RC", desc: "Zaryadlanish vaqt konstantasi" },
    ],
    visual: "|  |   ← plastinalar\n——  ——  ← dielektrik\nC = ε₀A/d",
    daily: [
      { icon: "📸", name: "Kamera flaşi", desc: "Kondensator tez razryadlanib kuchli nur beradi" },
      { icon: "💻", name: "Kompyuter RAM", desc: "DRAM kondensatorlarda bit-larni saqlaydi" },
      { icon: "⚡", name: "Defibrillyator", desc: "Yurak ritmini tiklash uchun kuchli zaryad chiqaradi" },
      { icon: "📱", name: "Sensorli ekran", desc: "Kapasitiv sensor barmog' zaryadini his qiladi" },
    ],
    fields: [
      { icon: "💻", field: "Elektronika", desc: "Deyarli barcha sxemalarda kondensator ishlatiladi" },
      { icon: "🏥", field: "Tibbiyot", desc: "Defibrillyator, EKG qurilmalari" },
      { icon: "⚡", field: "Energetika", desc: "Superkondensatorlar — tez zaryadlanadigan batareya alternativasi" },
    ],
    whyText: "Kondensatorsiz zamonaviy elektronika mavjud bo'lmas edi — CPU, RAM, radio, audio — barchasi kondensatorsiz ishlamaydi.",
    withoutIt: "Kompyuter, radio, televizor, tibbiy defibrillyator bo'lmas edi.",
    future: "Superkondensatorlar — elektr avtomobillarni 5 daqiqada zaryadlash imkonini berishi mumkin.",
    facts: [
      "Leyden bankida birinchi tajriba qilgan olim kuchli elektroshok oldi",
      "Zamonaviy superkondensator 1 kg da 30 Wh energiya saqlaydi",
    ],
    homeExp: "Ikkita metall plastina va plastik qatlam bilan oddiy kondensator yasab, multimetr bilan o'lchang.",
    labExp: "RC zanjirda zaryadlanish egri chizig'ini oscilloskop bilan kuzating, tau = RC ni hisoblang.",
    safety: "Zaryadlangan kondensatarga hech qachon to'g'ridan-to'g'ri tegmang — kuchli zarba berishi mumkin.",
  },

  magnetic: {
    title: "Magnit maydon",
    subtitle: "Elektr toki va magnit kuch",
    year: "1820",
    discoverer: "Hans Christian Orsted",
    country: "Daniya",
    historyStory: "1820-yilda Orsted ma'ruza paytida batareyani uladi va yonida turgan kompas ignasi burildi. Bu kutilmagan kuzatuv elektr va magnit hodisalarning bog'liqligini birinchi marta ko'rsatdi.",
    historyDev: [
      "1820 — Orsted kashfiyoti, Ampere elektromagnit nazariyasini boshladi",
      "1831 — Faraday elektromagnit induksiyani kashf etdi",
      "1864 — Maksvell to'liq elektromagnit nazariyasini yaratdi",
    ],
    whatSimple: "Magnit jismlar bir-birini tortadi yoki itaradi. Elektr toki oqayotgan o'tkazgich ham magnit maydon hosil qiladi — bu elektromagnetning asosi!",
    whatScientific: "B = μ₀I/(2πr) — to'g'ri o'tkazgich atrofidagi maydon. F = qv×B — harakatlanuvchi zaryadga ta'sir etuvchi kuch.",
    formulas: [
      { expr: "F = qv×B", desc: "Lorents kuchi (harakatlanuvchi zaryadga)" },
      { expr: "B = μ₀I/(2πr)", desc: "To'g'ri o'tkazgich maydon" },
      { expr: "Φ = B·A·cosθ", desc: "Magnit oqim" },
    ],
    visual: "I→\n↓\n⊙ B (halqalar)\n↓\nF⊥ = qvB",
    daily: [
      { icon: "🧲", name: "Doimiy magnitlar", desc: "Muzlatgich magnit, kompas, magnit bo'g'ich" },
      { icon: "💾", name: "Qattiq disk", desc: "Ma'lumotlar magnit qutblarda saqlanadi" },
      { icon: "🏥", name: "MRI", desc: "Tanani magnit maydon orqali tasvirga olish" },
      { icon: "🚂", name: "Maglev poyezd", desc: "Magnit yostiqda 600 km/soat — ishqalanishsiz harakat" },
    ],
    fields: [
      { icon: "🏥", field: "Tibbiyot", desc: "MRI — magnit-rezonans tomografiya, eng aniq tasvirlash" },
      { icon: "💻", field: "IT", desc: "Qattiq disk, magnit lenta ma'lumot saqlash" },
      { icon: "⚡", field: "Energetika", desc: "Generator va transformator — magnit induksiya asosida" },
    ],
    whyText: "Elektromagnit induksiya (Faraday) zamonaviy energetikaning asosi — elektr stantsiyalari, motor, generator.",
    withoutIt: "Elektr stantsiyasi, motor, generator, MRI — barchasi yo'q bo'lar edi.",
    future: "Termoyadroviy sintez reaktorlarida magnit maydon plazma ushlab turadi (Tokamak).",
    facts: [
      "Yer magnit maydoni kompasni yo'naltiradi va kosmik nurlardan himoya qiladi",
      "Maglev poyezdi 2015-da 603 km/soat rekord o'rnatdi",
    ],
    homeExp: "Batareya, mis sim va doimiy magnit bilan oddiy elektr motor yasash mumkin.",
    labExp: "Solenoyd hosil qilgan magnit maydonni Hall-sensor bilan o'lchab, I va B orasidagi bog'liqlikni grafika ola o'rganing.",
    safety: "Kuchli magnit qurilmalar (MRI) oldida temir buyumlar, kredit kartalar bo'lmasin.",
  },

  "em-wave": {
    title: "Elektromagnit to'lqin",
    subtitle: "Maksvell tenglamalari va yorug'lik",
    year: "1864",
    discoverer: "James Clerk Maxwell / Heinrich Hertz",
    country: "Shotlandiya / Germaniya",
    historyStory: "1864-yilda Maxwell elektr va magnit maydonlarining to'lqin ko'rinishida tarqalishi mumkinligini matematik yo'l bilan ko'rsatdi va uning tezligini hisobladi — yorug'lik tezligiga teng! 1888-yilda Hertz bu to'lqinlarni laboratoriyada hosil qildi.",
    historyDev: [
      "1864 — Maxwell tenglamalari, yorug'lik EMT ekanligini isbotladi",
      "1888 — Hertz birinchi radio to'lqinlarni hosil qildi",
      "1895 — Rentgen nurlarini kashf etdi",
      "1901 — Markoni transatlantik radio signalini uzatdi",
    ],
    whatSimple: "Radio, televizor, Wi-Fi, yorug'lik, rentgen — barchasi bir xil to'lqin, faqat chastotasi farq qiladi! Elektr va magnit maydonlari bir-birini hosil qilib, to'lqin shaklida tarqaladi.",
    whatScientific: "c = λ*f = 3×10⁸ m/s. EM to'lqin elektr va magnit maydonlarining tik yo'nalishda tebranishi.",
    formulas: [
      { expr: "c = λ·f", desc: "Yorug'lik tezligi = to'lqin uzunligi × chastota" },
      { expr: "E = hf", desc: "Foton energiyasi (Plank qonuni)" },
    ],
    visual: "Radio → Mikro → Infra → Ko'rinadigan → UV → Rentgen → Gamma\nf: ↑↑↑↑↑↑↑↑↑↑↑↑",
    daily: [
      { icon: "📻", name: "Radio", desc: "FM/AM radio to'lqinlari — millions km ga uzatiladi" },
      { icon: "📡", name: "Wi-Fi / Bluetooth", desc: "2.4 va 5 GHz mikro to'lqinlar" },
      { icon: "🥳", name: "Mobil aloqa", desc: "4G/5G — millimetrik to'lqinlar" },
      { icon: "🔬", name: "Rentgen", desc: "Suyak va to'qimalarni tasvirlash" },
    ],
    fields: [
      { icon: "📡", field: "Telekommunikatsiya", desc: "Radio, TV, internet, mobil aloqa" },
      { icon: "🏥", field: "Tibbiyot", desc: "Rentgen, MRI, lazer jarrohlik" },
    ],
    whyText: "EMT nazariyasi zamonaviy sivilizatsiyaning asosi: internet, mobil aloqa, tibbiy diagnostika.",
    withoutIt: "Radio, televizor, internet, mobil telefon, GPS, MRI — barchasi yo'q bo'lar edi.",
    future: "Terahertz to'lqinlar xavfsiz havo skaner, 6G texnologiyasi.",
    facts: [
      "Yorug'lik 1 sekundda 7.5 marta Yer atrofini aylanadi",
      "Bizgacha yetib keladigan kosmik mikro fon nurlanishi Big Bang dan 380,000 yil keyin hosil bo'lgan",
    ],
    homeExp: "AM radio va metall ekran bilan Faraday qafasini namoyish eting.",
    labExp: "Difraktsiya to'ri yordamida yorug'lik to'lqin uzunligini o'lchang.",
    safety: "Kuchli mikro to'lqin manbalaridan, ultrabinafsha nurdan uzoqda bo'ling.",
  },

  circuit: {
    title: "Elektr zanjiri",
    subtitle: "Ohm qonuni va Kirchhoff qoidalari",
    year: "1827",
    discoverer: "Georg Simon Ohm",
    country: "Germaniya",
    historyStory: "1827-yilda Ohm kuchlanish va tok orasidagi bog'liqlikni aniq o'lchab, V = I*R formulasini kashf etdi. Dastlab ko'plar bu kashfiyotni qabul qilmadi, lekin keyinchalik elektrotexnikaning asosi bo'ldi.",
    historyDev: [
      "1827 — Ohm qonuni",
      "1845 — Kirchhoff tok va kuchlanish qonunlarini berdi",
      "1947 — Birinchi tranzistor — zanjir nazariyasi yangi davr boshladi",
    ],
    whatSimple: "Batareyadan chiqgan tok — xuddi suvdek — rezistordan o'tib, yana batareyaga qaytadi. Kuchlanish katta → tok katta. Qarshilik katta → tok kichik.",
    whatScientific: "V = I*R (Ohm qonuni). Kirchhoff: sum(I) = 0 (tugun), sum(V) = 0 (kontur).",
    formulas: [
      { expr: "V = I·R", desc: "Ohm qonuni (Volt = Amper × Ohm)" },
      { expr: "P = I·V = I²R", desc: "Quvvat (Vatt)" },
    ],
    visual: "+—[R]—[R]—-\n|            |\n[V]          |\n|            |\n+-----------+",
    daily: [
      { icon: "💡", name: "Chiroq", desc: "Elektr toki o'tganda — issiqlik va yorug'lik" },
      { icon: "📱", name: "Telefon zaryadlagich", desc: "AC to'g'rilash, kuchlanishni kamaytirish" },
      { icon: "🚗", name: "Avtomobil", desc: "Akkumulator, starter, fara — elektr zanjirlar" },
    ],
    fields: [
      { icon: "💻", field: "Elektronika", desc: "Integral sxemalar — milliardlab tranzistorlar" },
      { icon: "⚡", field: "Elektrotexnika", desc: "Motor, generator, transformator dizayni" },
    ],
    whyText: "Ohm va Kirchhoff qonunlari elektrotexnikaning asosi — barcha elektron qurilmalar shu qonunlarga asoslanib loyihalanadi.",
    withoutIt: "Zamonaviy elektronika, elektr tarmoqlari, kompyuterlar bo'lmas edi.",
    future: "Kvant zanjirlar — klassik bitlar o'rniga qubit-lar bilan ishlash.",
    facts: [
      "iPhone 15 da 15 milliard dan ortiq tranzistor bor",
    ],
    homeExp: "LED, batareya va rezistor bilan oddiy chiroq zanjirini yig'ing.",
    labExp: "Multimetr bilan turli rezistorlar, parallel va ketma-ket zanjirlarning V, I, R larini o'lchang.",
    safety: "Hech qachon 25 V dan yuqori kuchlanishga qo'l tegizmang. Suv yaqinida elektr tajribalari qilmang.",
  },

  interference: {
    title: "To'lqin interferensiyasi",
    subtitle: "To'lqinlarning ustma-ust kelishi",
    year: "1801",
    discoverer: "Thomas Young",
    country: "Angliya",
    historyStory: "1801-yilda Thomas Young yorug'likni ikkita yaqin tirqishdan o'tkazdi va ekranda yoritilgan va qoraygan chiziqlar — interferensiya naqshi — hosil bo'ldi. Bu yorug'likning to'lqin tabiatini isbotladi.",
    historyDev: [
      "1801 — Young ikki tirqish tajribasi",
      "1887 — Michelson-Morley tajribasi — efirning yo'qligini interferometr bilan isbotladi",
      "2015 — LIGO gravitatsion to'lqin kashfiyoti — Nobel 2017",
    ],
    whatSimple: "Ikkita to'lqin bir joyga yetganda: bir xil fazada bo'lsa — kuchayadi (yorug'); teskari fazada bo'lsa — bekor qiladi (qorayadi). Xuddi ikkita to'lqin havzasidagi suvdek!",
    whatScientific: "Konstruktiv: delta = m*lambda. Destruktiv: delta = (m+0.5)*lambda. Young: d*sin(theta) = m*lambda.",
    formulas: [
      { expr: "d·sinθ = mλ", desc: "Young tirqish formulasi" },
      { expr: "Δ = mλ", desc: "Konstruktiv interferensiya sharti" },
    ],
    visual: "⊙—→——[||]——→ maksimum\n        ↕\n        → minimum",
    daily: [
      { icon: "🌈", name: "Sovun pufakchasi", desc: "Qatlam qalinligiga qarab turli ranglar ko'rinadi" },
      { icon: "💿", name: "CD/DVD disk", desc: "Yorug'lik interferensiyasi kamalak hosil qiladi" },
      { icon: "🔬", name: "Interferometrik mikroskop", desc: "Nanotreatment uchun o'ta aniq o'lchash" },
    ],
    fields: [
      { icon: "🔬", field: "Optika", desc: "Linzalar, ko'zoynak, lazer qurilmalar sifati nazorati" },
      { icon: "🔭", field: "Astronomiya", desc: "Interferometrik teleskoplar" },
    ],
    whyText: "Interferensiya holografiyani, lazer texnologiyasini va LIGO orqali gravitatsion to'lqinlar kashfiyotini imkonli qildi.",
    withoutIt: "Holografiya, lazer sanoati, LIGO yo'q bo'lar edi.",
    future: "Kvant interferensiya — kvant kompyuterlar va kriptografiya asosi.",
    facts: [
      "LIGO proton diametridan 1000 marta kichik harakatni o'lcholdi",
      "2015 — birinchi gravitatsion to'lqin kashfiyoti Nobel 2017 mukofotiga sazovor bo'ldi",
    ],
    homeExp: "Sovun pufakchasi va kuchli chiroq bilan interferensiya ranglarini kuzating.",
    labExp: "Lazer va ikkita tirqish bilan interferensiya naqshini ekranda hosil qilib, to'lqin uzunligini hisoblang.",
    safety: "Lazer nuriga hech qachon bevosita qaramang.",
  },

  refraction: {
    title: "Yorug'lik sinishi",
    subtitle: "Snell qonuni va optik linzalar",
    year: "1621",
    discoverer: "Willebrord Snellius",
    country: "Niderlandiya",
    historyStory: "1621-yilda Snell yorug'likning ikki muhit chegarasida sinishini o'rganib, burchaklar sinuslarining nisbati doimiy ekanligini kashf etdi. Bu ko'zoynak, teleskop va mikroskopning nazariy asosi bo'ldi.",
    historyDev: [
      "1621 — Snell qonuni kashf etildi",
      "1668 — Newton prizma bilan yorug'likni spektrga ajratdi",
      "1900s — Optik tolali aloqa — sinish orqali ma'lumot uzatish",
    ],
    whatSimple: "Yorug'lik suvga kirganda u bukiladi. Shuning uchun suvdagi tayoq egri ko'rinadi! Ko'zoynaklar shu printsip asosida ishlaydi.",
    whatScientific: "n₁*sinθ₁ = n₂*sinθ₂ (Snell qonuni). n = c/v — sindirish ko'rsatkichi.",
    formulas: [
      { expr: "n₁sinθ₁ = n₂sinθ₂", desc: "Snell qonuni" },
      { expr: "n = c/v", desc: "Sindirish ko'rsatkichi" },
    ],
    visual: "——|——————\n   ↘️ havo n₁\n   |sinishi\n   ↘️ suv n₂ (katta)",
    daily: [
      { icon: "🔍", name: "Ko'zoynak", desc: "Linzalar yorug'likni sindirish orqali ko'rishni tuzatadi" },
      { icon: "💎", name: "Olmos", desc: "Yuqori sindirish ko'rsatkichi — kamalak effekti" },
      { icon: "🌈", name: "Kamalak", desc: "Suv tomchilari yorug'likni sindiradi va spektrga ajratadi" },
      { icon: "🔭", name: "Teleskop va mikroskop", desc: "Linzalar yordamida kattalashtirish" },
    ],
    fields: [
      { icon: "🔬", field: "Optika", desc: "Linza, prizma, ko'zoynak, lazer" },
      { icon: "💻", field: "Telekommunikatsiya", desc: "Optik tolali internet kabellar" },
    ],
    whyText: "Sinish qonuni optik asboblar (ko'zoynak, teleskop, mikroskop) va internet (optik tola) asosini tashkil etadi.",
    withoutIt: "Ko'zoynak, mikroskop, teleskop, optik tolali internet yo'q bo'lar edi.",
    future: "Metamateriallar — manfiy sindirish ko'rsatkichlisi — ko'rinmas qilish texnologiyasi.",
    facts: [
      "Optik tola yorug'lik tezligining 67% da ma'lumot uzatadi",
      "Olmos sindirish ko'rsatkichi n=2.42 — eng yuqorilardan biri",
    ],
    homeExp: "Stakan suvga qo'shiq soling — ustidan qaraydigan qoshiq bukilib ko'rinadi.",
    labExp: "Prizma orqali yorug'likni spektrga ajratib, har rangning to'lqin uzunligini hisoblang.",
    safety: "Lazer nuriga hech qachon bevosita qaramang.",
  },

  diffraction: {
    title: "Difraksiya",
    subtitle: "To'lqinning to'siq atrofida egrilishi",
    year: "1665",
    discoverer: "Francesco Maria Grimaldi",
    country: "Italiya",
    historyStory: "1665-yilda Grimaldi yorug'likni tirqishdan o'tkazib, u to'g'ri o'tmay, egrilib tarqalishini kuzatdi va bu hodisaga diffractio deb nom berdi.",
    historyDev: [
      "1665 — Grimaldi difraksiyani kashf etdi",
      "1912 — Laue rentgen difraksiyasini kristallarda isbotladi",
      "1952 — Rosalind Franklin difraksiya naqshidan DNK tuzilmasini aniqladi",
    ],
    whatSimple: "To'lqin kichik tirqish yoki to'siq orqali o'tganda, u hamma tomonga tarqaladi — xuddi tovush eshik tirqishidan o'tib, butun xonaga tarqalgani kabi.",
    whatScientific: "Huygens printsipi: har bir to'lqin fronti nuqtasi yangi to'lqin manbai. Bragg qonuni: 2d*sin(theta) = n*lambda.",
    formulas: [
      { expr: "sinθ = λ/d", desc: "Birinchi minimum burchagi (d — tirqish eni)" },
      { expr: "2d·sinθ = nλ", desc: "Bragg qonuni (kristall difraksiyasi)" },
    ],
    visual: "—[|]—\n    ↓\n   )X(\n  (sektor)",
    daily: [
      { icon: "🎵", name: "Ovoz tarqalishi", desc: "Tovush eshik orqasida ham eshitiladi — difraksiya" },
      { icon: "🌈", name: "CD disk ranglari", desc: "Difraksiya to'ri kamalak hosil qiladi" },
      { icon: "🔬", name: "Elektron mikroskopi", desc: "Elektronlar difraksiyasidan kristal tuzilmasini aniqlash" },
    ],
    fields: [
      { icon: "🔬", field: "Kristallografiya", desc: "DNK, oqsillar, minerallar tuzilmasini aniqlash" },
      { icon: "📡", field: "Antennalar", desc: "Difraksiya burchagi optimallashtirish" },
    ],
    whyText: "DNK ikki spiral tuzilmasi difraksiya usuli bilan kashf etildi — bu biologiya va tibbiyotni o'zgartirib yubordi.",
    withoutIt: "DNK tuzilmasi, kristallografiya, zamonaviy biologiya kechikib rivojlangan bo'lar edi.",
    future: "Lazer difraksiya — nanomateriallar sifatini nazorat qilish.",
    facts: [
      "DNK tuzilmasi (1953) difraksiya rentgeni orqali kashf etildi",
      "Elektronlar ham to'lqin kabi difraksiyalanadi",
    ],
    homeExp: "CD diskini chiroq yaqiniga tutib, difraksiya ranglarini ko'ring.",
    labExp: "Lazer va difraksiya to'ri bilan to'lqin uzunligini aniq o'lchang.",
    safety: "Lazer nuridan ko'zni himoya qiling.",
  },

  resonance: {
    title: "Rezonans va ovoz",
    subtitle: "Tabiiy chastota va tebranish kuchayishi",
    year: "1638",
    discoverer: "Galileo Galilei",
    country: "Italiya",
    historyStory: "1638-yilda Galileo tabiiy chastota va rezonans tushunchalarini birinchi bo'lib tushuntirdi. 1940-yilda Tacoma Narrows ko'prigi rezonans tufayli qulab tushishi — bu hodisaning kuchini namoyish etdi.",
    historyDev: [
      "1638 — Galileo rezonans tushunchasini tasvirlab berdi",
      "1940 — Tacoma Narrows ko'prigi shamol rezonansidan qulab tushdi",
      "1950s — NMR (yadro magnit rezonans) — MRI ning asosi",
    ],
    whatSimple: "Har jismning tabiiy tebranish chastotasi bor. Agar tashqi kuch shu chastotada ta'sir qilsa — tebranish tobora kuchayib boradi. Opera qo'shiqchisi shisha idishni o'z tovushi bilan sindirishi mumkin!",
    whatScientific: "Rezonans chastotasi omega0 = sqrt(k/m). So'numlangan holda Q-factor tebranish sifatini ko'rsatadi.",
    formulas: [
      { expr: "ω₀ = √(k/m)", desc: "Rezonans (tabiiy) chastota" },
      { expr: "Q = ω₀/Δω", desc: "Sifat faktori — rezonans keskinligi" },
    ],
    visual: "f_tashqi = f_tabiiy\n→ KUCHAYISH! ↑↑↑",
    daily: [
      { icon: "🎻", name: "Musiqa asboblari", desc: "Tor, qo'ng'iroq, nay — rezonans orqali tovush hosil qiladi" },
      { icon: "📻", name: "Radio tuner", desc: "Kerakli stansiya chastotasiga moslashtirish" },
      { icon: "🍜", name: "Mikroto'lqin pech", desc: "2.45 GHz — suv molekulalarining tabiiy chastotasi" },
    ],
    fields: [
      { icon: "🎵", field: "Akustika", desc: "Musiqa zali, mikrofon, dinamik dizayni" },
      { icon: "🏥", field: "Tibbiyot", desc: "MRI — magnit-rezonans tomografiya" },
    ],
    whyText: "Rezonans MRIni yaratdi — zamonaviy tibbiyotning eng muhim diagnostika asbobini.",
    withoutIt: "MRI, musiqa asboblari, radio tunerlar bo'lmas edi.",
    future: "Optomexanik rezonans — kvant o'lchovlar uchun.",
    facts: [
      "Tacoma ko'prigi 4 oy ichida qulab tushdi",
      "Opera qo'shiqchisi 100 dB tovush bilan shisha sindira oladi",
    ],
    homeExp: "Shisha bardoqni ho'l barmog'ingizni aylantirish orqali kuylating.",
    labExp: "Surge va prujina sistemasida rezonans chastotasini o'lchab, omega0 formulasini tasdiqlang.",
    safety: "Katta ovoz tebranishlari yaqinida quloq himoyasi kering.",
  },

  gas: {
    title: "Ideal gaz molekulalari",
    subtitle: "Boyl-Mariott va ideal gaz qonuni",
    year: "1662",
    discoverer: "Robert Boyle / Gay-Lussac / Avogadro",
    country: "Irlandiya / Fransiya / Italiya",
    historyStory: "1662-yilda Robert Boyle gaz hajmi va bosim orasidagi teskari proporsionallikni kashf etdi. Keyinchalik Gay-Lussac harorat va bosim, Avogadro mollar va hajm bog'liqligini qo'shdi.",
    historyDev: [
      "1662 — Boyle qonuni: PV = const (T = const)",
      "1802 — Gay-Lussac: V/T = const (P = const)",
      "1860 — Maxwell-Boltzmann taqsimot — molekulyar kinetik nazariya",
    ],
    whatSimple: "Gaz — ko'rinmas mayda zarralar. Ular tez harakatlanadi va idish devoriga urilib bosim hosil qiladi. Harorat ortsa — zarralar tezlashadi — bosim ortadi.",
    whatScientific: "pV = nRT (R = 8.314 J/mol*K). Molekulyar kinetik energiya: E = (3/2)*k*T.",
    formulas: [
      { expr: "pV = nRT", desc: "Ideal gaz tenglamasi" },
      { expr: "E = (3/2)kT", desc: "Molekulyar kinetik energiya" },
    ],
    visual: "[ . . . . ]\n[. ↗️. ↙️.]\n[ . . . . ]\nBosim = zarba/S",
    daily: [
      { icon: "🚗", name: "Avtomobil shinasi", desc: "Havo harorat o'zgarganda bosim o'zgaradi" },
      { icon: "🔥", name: "Pech va isitgich", desc: "Tabiiy gaz yonishi — ekzotermik reaksiya" },
      { icon: "🏄", name: "Sho'ng'uvchi", desc: "Chuqurlikda havo ballon hajmi o'zgaradi" },
    ],
    fields: [
      { icon: "⚙️", field: "Mashinasozlik", desc: "DVS, kompressor, turbina dizayni" },
      { icon: "🌬️", field: "Meteorologiya", desc: "Atmosfera bosimi, ob-havo bashorat" },
    ],
    whyText: "Ideal gaz qonuni isitish, siqish, yoqilg'i yonish — barcha sanoat jarayonlarining asosi.",
    withoutIt: "Dvigatel, gaz turbina, kompressor — ularni hisoblash imkonsiz bo'lar edi.",
    future: "Kvant gaz — ultrasovuq atomlar, Bose-Einstein kondensati.",
    facts: [
      "Yer atmosferasida 5.15*10^18 kg gaz bor",
    ],
    homeExp: "Bosiq shishani issiq va sovuq suvga solib, hajm o'zgarishini kuzating.",
    labExp: "Shprits yordamida Boyl qonunini P va V o'lchab tasdiqlang.",
    safety: "Gaz silindrlari bilan tajriba qilganda qo'shimcha bosim qoidalariga rioya qiling.",
  },

  heat: {
    title: "Issiqlik uzatilishi",
    subtitle: "Konduktiv, konvektiv va radiativ issiqlik",
    year: "1822",
    discoverer: "Joseph Fourier",
    country: "Fransiya",
    historyStory: "1822-yilda Fourier Issiqlik analitik nazariyasi kitobini chop etdi va issiqlik tarqalishining matematik tenglamasini berdi.",
    historyDev: [
      "1822 — Fourier issiqlik qonunini yaratdi",
      "1850 — Stefan-Boltzmann radiativ issiqlik qonuni",
      "1900 — Plank kvant radatsiya nazariyasi",
    ],
    whatSimple: "Issiqlik uch yo'l bilan tarqaladi: tegish orqali (metall qoshiq isiydi), oqim orqali (issiq havo ko'tariladi), nurlanish orqali (quyosh nuri kosmosda ham isitadi).",
    whatScientific: "Fourier qonuni: q = -k*A*(dT/dx). Stefan-Boltzmann: P = sigma*T^4.",
    formulas: [
      { expr: "q = -k·A·ΔT/Δx", desc: "Fourier qonuni (konduktiv issiqlik oqimi)" },
      { expr: "P = εσT⁴·A", desc: "Stefan-Boltzmann (radiatsiya)" },
    ],
    visual: "🔥 issiq\n↓ konduktiv\n❄️ sovuq\n\nKonvektiv: 🔥 → ☁️\nRadiativ: 🔥 ~~→",
    daily: [
      { icon: "🍳", name: "Pishirish", desc: "Plita — konduktiv; pech — konvektiv; grill — radiativ" },
      { icon: "❄️", name: "Muzlatgich", desc: "Issiqlikni olib sovuq saqlanadi" },
      { icon: "💻", name: "Kompyuter sovutgich", desc: "CPU issiqligini konduktiv va konvektiv olib ketadi" },
    ],
    fields: [
      { icon: "⚙️", field: "Mashinasozlik", desc: "Dvigatel sovutish, turbina va reaktor issiqlik boshqaruvi" },
      { icon: "🏗️", field: "Qurilish", desc: "Bino izolyatsiyasi, energiya tejash" },
    ],
    whyText: "Issiqlik uzatilish qonunlari dvigatel, elektrstantsiya, uy izolyatsiyasi — energiya texnologiyasining asosi.",
    withoutIt: "Zamonaviy energetika, muhendislik, qurilish ancha murakkab bo'lar edi.",
    future: "Termoelektrik generatorlar — chiqindi issiqlikni elektr energiyasiga aylantirish.",
    facts: [
      "Quyosh 4*10^26 W energiya nurlatadi",
      "Insonning tanasi ~80 W issiqlik chiqaradi",
    ],
    homeExp: "Turli materiallardan qoshiq qilib, uchini issiq suvga soling — qaysi biri tezroq isiydi?",
    labExp: "Turli materiallarning issiqlik o'tkazuvchanligini temperatura gradienti o'lchovidan toping.",
    safety: "Issiq yuzalardan ehtiyot bo'ling, o'choq qurilmalarida himoya qo'lqop ishlating.",
  },

  carnot: {
    title: "Karno sikli",
    subtitle: "Termodinamikaning 2-qonuni va maksimal FIK",
    year: "1824",
    discoverer: "Sadi Carnot",
    country: "Fransiya",
    historyStory: "1824-yilda 27 yoshli fransuz muhandisi Sadi Carnot Olovning harakat kuchi haqida mulohazalar kitobini yozdi. Unda u ideal issiqlik mashinasining maksimal samaradorligini hisobladi. Afsuski, u 36 yoshida vafot etdi.",
    historyDev: [
      "1824 — Carnot ideal siklni nazariy tasvirladi",
      "1850 — Clausius termodinamikaning 2-qonunini yaratdi (entropiya)",
      "1851 — Lord Kelvin mutlaq harorat shkalasini kiritdi",
    ],
    whatSimple: "Hech qanday dvigatel 100% samarali bo'la olmaydi — bir qismi doimo isitish sifatida yo'qoladi. Carnot isbotladi: maksimal FIK faqat haroratlarga bog'liq.",
    whatScientific: "Carnot FIK: eta = 1 - T_c/T_h. Termodinamikaning 2-qonuni: entropiya hech qachon kamaymasligiga kafolat beradi.",
    formulas: [
      { expr: "η = 1 - T_c/T_h", desc: "Carnot samaradorligi (T — absolyut harorat, Kelvin)" },
      { expr: "ΔS ≥ 0", desc: "Entropiya saqlanishi (termod. 2-qonun)" },
    ],
    visual: "T_issiq\n  ↓ Q_h\n[DVIGATEL]\n  ↓ Q_c\nT_sovuq\nη = W/Q_h",
    daily: [
      { icon: "🚗", name: "Avtomobil dvigatel", desc: "Yonilg'i 800C — chiqma gaz 300C — eta ~ 25-30%" },
      { icon: "✈️", name: "Samolyot turbinasi", desc: "Yuqori harorat — yuqori samaradorlik" },
      { icon: "🔥", name: "Elektr stantsiyasi", desc: "Bug' turbinasi — issiqlikdan elektr" },
    ],
    fields: [
      { icon: "⚡", field: "Elektr energetikasi", desc: "Bug' turbina elektr stantsiyalar — FIK optimizatsiya" },
      { icon: "🚗", field: "Transport", desc: "DVS, turboreaktiv dvigatel samaradorligi" },
    ],
    whyText: "Carnot ishi termodinamikaning 2-qonuniga asos bo'ldi — bu qonun vaqt o'qini belgilab, koinotning asosiy qonunlaridan.",
    withoutIt: "Zamonaviy elektr stantsiyalari, dvigatellar, muzlatgichlar samaradorligi hisoblash imkonsiz bo'lar edi.",
    future: "Issiqlik nasoslar, superkritik bug' turbinalar — yuqori haroratda eta > 50%.",
    facts: [
      "Quyosh paneli FIK atigi 20-25% — Carnot chegarasi buni cheklaydi",
      "Hech qanday dvigatel 100% samarali bo'la olmaydi — bu fizika qonuni",
    ],
    homeExp: "Issiq qo'l va sovuq stol — issiqlik sovuqdan issiqqa o'tmasligini (faqat energiya sarflabgina) kuzating.",
    labExp: "Stirling dvigatelni yig'ib, harorat gradientiga bog'liq ravishda FIK ni o'lchang.",
    safety: "Yuqori haroratli jihozlar (bug' manba) bilan ehtiyotkorlik kerak.",
  },

  tunnel: {
    title: "Kvant tunnel effekti",
    subtitle: "To'siqdan o'tib ketish",
    year: "1928",
    discoverer: "Friedrich Hund / George Gamow",
    country: "Germaniya",
    historyStory: "1928-yilda Gamow alfa-radioaktivlikni tushuntirish uchun kvant tunnel effektini ishlatdi — atom yadrosidan chiqib ketishi uchun energetik to'siqni tunnel orqali o'tishi mumkin. Klassik fizika bunga ruxsat bermagan bo'lar edi.",
    historyDev: [
      "1928 — Gamow tunnel effektini alfa-parchalanishda ishlatdi",
      "1960 — Esaki tunnel diodini ixtiro qildi (Nobel 1973)",
      "1981 — Binning va Rohrer STM mikroskopini yaratdi (Nobel 1986)",
    ],
    whatSimple: "Kvant dunyosida zarralar devordan o'tib ketishi mumkin! Klassik fizikada bu mumkin emas edi. Lekin kvant zarrachasi tunnel ochib o'tadi.",
    whatScientific: "Tunneling ehtimoli: T ~ exp(-2*kappa*d), kappa = sqrt(2m(V0-E))/hbar.",
    formulas: [
      { expr: "T ≈ e^{-2κd}", desc: "Tunneling ehtimoli (d — to'siq eni)" },
      { expr: "κ = √(2m(V₀-E))/ℏ", desc: "Zaiflash koeffitsienti" },
    ],
    visual: "E ——————\n         |  V₀\n——————  |  ——————\n Zarracha ~~→ tunnel",
    daily: [
      { icon: "💻", name: "Flash xotira (USB, SSD)", desc: "Elektronlar FET tranzistor to'sig'idan tunnel qiladi" },
      { icon: "🔬", name: "STM mikroskopi", desc: "Atom darajasida sirt tasvirlash — tunnel toki o'lchov" },
      { icon: "☀️", name: "Quyosh reaksiyalari", desc: "Quyoshda protonlar tunnel qilib sintez reaksiyalarini ta'minlaydi" },
    ],
    fields: [
      { icon: "💻", field: "Mikroelektronika", desc: "Flash-xotira, tunnel diod, FET tranzistor" },
      { icon: "🔬", field: "Nanotexnologiya", desc: "STM mikroskopi atomlarni ko'rish va joylashtirish" },
    ],
    whyText: "Tunnel effekti zamonaviy Flash-xotirani (USB, SSD, telefon) imkonli qildi.",
    withoutIt: "Flash-xotira, SSD, USB disklar, zamonaviy smartfonlar bo'lmas edi.",
    future: "Kvant kompyuterlar uchun kvant tunnel o'tishlari, molekulyar elektronika.",
    facts: [
      "SSD diskingizda million marta tunnel effekti sodir bo'ladi",
      "STM bilan bitta atomni ko'rish va joy almashtirisih mumkin",
    ],
    homeExp: "STM printsipi: simning uchini metall yuzasiga juda yaqin keltiring va tok o'lchang.",
    labExp: "Esaki tunnel diodining I-V xarakteristikasini o'lchab, tunnel o'tishini ko'rsating.",
    safety: "Kvant tajribalari maxsus laboratoriya sharoitida bajariladi.",
  },

  "wave-particle": {
    title: "To'lqin-zarra dualizmi",
    subtitle: "De Broglie to'lqin uzunligi",
    year: "1924",
    discoverer: "Louis de Broglie",
    country: "Fransiya",
    historyStory: "1924-yilda de Broglie o'z doktorlik dissertatsiyasida barcha moddiy zarralar — elektronlar, protonlar, hatto molekulalar — to'lqin xususiyatiga ega degan gipotezasini taklif etdi. Einstein shu ishni o'qib hayratda qoldi. De Broglie 1929-yilda Nobel mukofotini oldi.",
    historyDev: [
      "1924 — De Broglie gipotezasi",
      "1927 — Davisson va Germer elektronlar difraksiyasini eksperimentda isbotladi",
      "1961 — Jonsson bitta elektron bilan ikki tirqish tajribasini o'tkazdi",
    ],
    whatSimple: "Elektronlar — va barcha zarralar — zarracha kabi ham, to'lqin kabi ham harakat qiladi! Kuzatilganda — zarracha; kuzatilmaganda — to'lqin. Bu kvant dunyosining eng g'aroyib tomoni.",
    whatScientific: "lambda = h/p — de Broglie to'lqin uzunligi. Bitta elektron ham interferensiya naqshi hosil qiladi!",
    formulas: [
      { expr: "λ = h/p = h/(mv)", desc: "De Broglie to'lqin uzunligi" },
      { expr: "ΔxΔp ≥ ℏ/2", desc: "Geyzenberg noaniqlik prinsipi" },
    ],
    visual: "Elektron →\n[||] tirqish\n━━━━━━━━\n🌊 interferensiya!",
    daily: [
      { icon: "🔬", name: "Elektron mikroskopi", desc: "Elektronlar qisqa to'lqin — atomlarni ko'rish mumkin" },
      { icon: "💊", name: "Dori molekulalari", desc: "Kvant kimyo — molekulalar dizayni to'lqin funksiya asosida" },
      { icon: "💻", name: "Kvant kompyuter", desc: "Qubitlar to'lqin-zarracha dualizmidan foydalanadi" },
    ],
    fields: [
      { icon: "🔬", field: "Nanotexnologiya", desc: "Atom va molekulalarni kvant effektlar orqali boshqarish" },
      { icon: "💻", field: "Kvant hisoblash", desc: "Kvant kompyuterlar printsipiy asosi" },
    ],
    whyText: "To'lqin-zarracha dualizmi kvant mexanikasining yuragida turadi. Zamonaviy elektronika, kimyo, farmakologiya — hammasi shu tushunchaga asoslanadi.",
    withoutIt: "Elektron mikroskop, kvant kimyo, zamonaviy yarim o'tkazgichlar texnologiyasi bo'lmas edi.",
    future: "Kvant kompyuterlar, kvant teleportatsiya, kvant kriptografiya.",
    facts: [
      "Elektron mikroskopi yorug'lik mikroskopidan 1000 marta ko'proq kattalashtiradi",
      "1998 — 60 ta atomli fullerene (C60) ham to'lqin xususiyatini ko'rsatdi",
    ],
    homeExp: "Ikki tirqish animatsiyasini internet-da topib, bitta fotonning interferensiya naqshini kuzating.",
    labExp: "Elektron difraksiya trubkasida de Broglie to'lqin uzunligini o'lchang.",
    safety: "Kvant tajribalari maxsus laboratoriya sharoitida bajariladi.",
  },

  photoeffect: {
    title: "Fotoeffekt",
    subtitle: "Yorug'lik kvanti va Einstein Nobel mukofoti",
    year: "1887 / 1905",
    discoverer: "Heinrich Hertz (kashf) / Albert Einstein (tushuntirish)",
    country: "Germaniya",
    historyStory: "1887-yilda Hertz yorug'lik metallga tushganda elektron chiqishini sezdi — lekin tushuntirolmadi. 1905-yilda Einstein kvant nazariyasini qo'llab, yorug'lik fotonlar to'plamidan iborat ekanligini isbotladi. Einstein 1921-yilda fotoeffekt uchun Nobel mukofoti oldi.",
    historyDev: [
      "1887 — Hertz tasodifan fotoeffektni kashf etdi",
      "1900 — Plank kvant nazariyasiga asos soldi",
      "1905 — Einstein foton tushunchasini kiritdi — annus mirabilis yili",
      "1954 — Birinchi quyosh paneli ixtiro qilindi",
    ],
    whatSimple: "Yorug'lik metallga tushganda, elektronlar uchib chiqadi! Kuchliroq yorug'lik ko'proq elektron chiqaradi, lekin har bir elektron tezroq ucha olmaydi — faqat chastota ko'tarilsa tezlashadi.",
    whatScientific: "E_kinetik = h*f - phi (phi — ish funksiya). Foton energiyasi E = h*f.",
    formulas: [
      { expr: "E_k = hf - φ", desc: "Elektronning kinetik energiyasi (h — Plank, f — chastota, phi — ish funksiya)" },
      { expr: "E = hf = hc/λ", desc: "Foton energiyasi" },
    ],
    visual: "hf →\n  ↓ foton\n[METALL] → e⁻ → elektron",
    daily: [
      { icon: "☀️", name: "Quyosh paneli", desc: "Fotonlar yarimo'tkazgichda elektron chiqarib, elektr hosil qiladi" },
      { icon: "📸", name: "Raqamli kamera", desc: "CCD va CMOS sensorlar fotoeffekt asosida ishlaydi" },
      { icon: "🌞", name: "Fotosensitiv sensor", desc: "Avtomatik eshiklar, yorug'lik sensorlari" },
      { icon: "💡", name: "LED va lazer diod", desc: "Teskari fotoeffekt — elektr yorug'likka" },
    ],
    fields: [
      { icon: "☀️", field: "Quyosh energetikasi", desc: "Fotovoltaik quyosh panellari — barqaror energiya" },
      { icon: "📸", field: "Optika va tasvirlash", desc: "Kamera, sensor, fotodetektor" },
      { icon: "🔐", field: "Kvant kriptografiya", desc: "Bir fotonli kvant aloqa kanallari" },
    ],
    whyText: "Fotoeffekt quyosh energetikasini va raqamli fotografiyani yaratdi. Einstein Nobel mukofoti nisbiylik uchun emas — aynan fotoeffekt uchun berilgan.",
    withoutIt: "Quyosh panellari, raqamli kameralar, yorug'lik sensorlari, kvant optika yo'q bo'lar edi.",
    future: "Perovskite quyosh panellari — arzonroq va samaraliroq. Kvant optika.",
    facts: [
      "Birinchi quyosh panelning FIK atigi 6% bo'lgan — hozir 26%+",
      "Einstein Nobel mukofoti nisbiylik uchun emas, fotoeffekt uchun berilgan",
      "Ko'z to'rqon hujayralari ham fotoeffektga o'xshash mexanizm bilan ishlaydi",
    ],
    homeExp: "Quyosh kalkulyatorini turli yorug'lik manbalari ostida va qo'l bilan to'sib kuzating.",
    labExp: "Fotoqovushqoq vosita yordamida turli chastotali yorug'lik uchun to'siq kuchlanishni o'lchab, Plank konstantasini hisoblang.",
    safety: "UV va lazer nurlaridan ko'zni himoya qiling.",
  },
}
