[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn config.wsgi --workers 1 --threads 2 --worker-class gthread --max-requests 500 --max-requests-jitter 50 --log-file - --bind 0.0.0.0:$PORT"
