web: gunicorn config.wsgi --workers 1 --threads 2 --worker-class gthread --max-requests 500 --max-requests-jitter 50 --log-file - --bind 0.0.0.0:$PORT
release: python manage.py migrate --noinput && python manage.py collectstatic --noinput
