# Generated by Django 5.1.15 on 2026-05-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Darslik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='Sinf')),
                ('subject', models.CharField(max_length=100, verbose_name='Fan nomi')),
                ('subtitle', models.CharField(max_length=200, verbose_name="Qo'shimcha sarlavha")),
                ('icon', models.CharField(default='📚', max_length=10, verbose_name='Emoji icon')),
                ('color', models.CharField(default='#34D399', max_length=20, verbose_name='Asosiy rang')),
                ('accent', models.CharField(default='#059669', max_length=20, verbose_name='Accent rang')),
                ('formulas', models.JSONField(default=list, verbose_name='Formulalar')),
                ('chapters', models.IntegerField(default=0, verbose_name='Boblar soni')),
                ('pages', models.IntegerField(default=0, verbose_name='Sahifalar soni')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='darsliklar/pdf/', verbose_name='PDF fayl')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Darslik',
                'verbose_name_plural': 'Darsliklar',
                'ordering': ['grade', 'order'],
            },
        ),
    ]
