# Generated by Django 6.0.5 on 2026-05-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darsliklar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='darslik',
            name='mavzular',
            field=models.JSONField(blank=True, default=list, help_text='[{"mavzu": "Mexanika asoslari", "bet": 12}, ...]', verbose_name='Mavzular'),
        ),
    ]
