# Generated by Django 6.0.5 on 2026-05-22 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darsliklar', '0002_darslik_mavzular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mavzu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mavzu', models.CharField(max_length=300, verbose_name='Mavzu nomi')),
                ('bet', models.IntegerField(verbose_name='Bet raqami')),
                ('bob', models.IntegerField(blank=True, default=0, verbose_name='Bob raqami')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('darslik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mavzu_set', to='darsliklar.darslik', verbose_name='Darslik')),
            ],
            options={
                'verbose_name': 'Mavzu',
                'verbose_name_plural': 'Mavzular',
                'ordering': ['darslik__grade', 'bob', 'order', 'bet'],
            },
        ),
    ]
