# Generated by Django 6.0.5 on 2026-05-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darsliklar', '0003_mavzu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='darslik',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='mavzu',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='mavzular/pdf/', verbose_name='PDF fayl'),
        ),
    ]
