# Generated by Django 6.0.5 on 2026-05-15 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('text', 'Matn darsi'), ('video', 'Video dars'), ('slide', 'Slayd darsi'), ('mixed', 'Aralash (matn + video)')], default='mixed', max_length=10),
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha')),
                ('content', models.TextField(blank=True, verbose_name='Matn / formula (Markdown)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slides/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Slayd',
                'verbose_name_plural': 'Slaydlar',
                'ordering': ['order'],
            },
        ),
    ]
