# Generated by Django 6.0.5 on 2026-05-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulatsiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('slug', models.SlugField(help_text='Frontendda qaysi 3D komponent yuklanishini belgilaydi. Masalan: pendulum', unique=True, verbose_name='Slug (komponent ID)')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('kategoriya', models.CharField(choices=[('mexanika', 'Mexanika'), ('elektr', 'Elektr va Magnit'), ('optika', 'Optika'), ('termodinamika', 'Termodinamika'), ('kvant', 'Kvant fizikasi'), ('boshqa', 'Boshqa')], default='mexanika', max_length=20, verbose_name='Kategoriya')),
                ('parametrlar', models.JSONField(blank=True, default=dict, help_text='JSON formatda. Masalan: {"uzunlik": {"label": "Uzunlik (m)", "min": 0.5, "max": 3.0, "default": 1.0, "step": 0.1}}', verbose_name='Parametrlar')),
                ('formula', models.CharField(blank=True, help_text='Masalan: T = 2π√(L/g)', max_length=255, verbose_name='Formula')),
                ('info_text', models.TextField(blank=True, help_text="Simulatsiya ostida ko'rinadigan tushuntirish matni", verbose_name="Qo'shimcha ma'lumot")),
                ('icon_name', models.CharField(default='Atom', help_text='Lucide icon nomi: Atom, Clock, Zap, Waves, Thermometer ...', max_length=50, verbose_name='Icon nomi')),
                ('color', models.CharField(default='text-blue-400', help_text='Masalan: text-blue-400, text-yellow-400, text-purple-400', max_length=60, verbose_name='Rang (Tailwind class)')),
                ('tez_orada', models.BooleanField(default=False, help_text='Yoqilsa simulatsiya o\'chiriladi va "Tez orada" belgisi chiqadi', verbose_name='"Tez orada" belgisi')),
                ('is_published', models.BooleanField(default=True, verbose_name='Nashr etilgan')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Simulatsiya',
                'verbose_name_plural': '3D Simulatsiyalar',
                'ordering': ['order', 'title'],
            },
        ),
    ]
