# Generated by Django 6.0.5 on 2026-05-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kashfiyot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='kashfiyotlar/', verbose_name='Rasm')),
                ('kategoriya', models.CharField(choices=[('ixtiro', 'Ixtiro'), ('tajriba', 'Tajriba'), ('olim', 'Olim'), ('rekord', 'Rekord'), ('boshqa', 'Boshqa')], default='boshqa', max_length=20, verbose_name='Kategoriya')),
                ('is_published', models.BooleanField(default=True, verbose_name='Nashr etilgan')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Kashfiyot',
                'verbose_name_plural': 'Kashfiyotlar',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
