# Generated by Django 6.0.5 on 2026-05-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kashfiyotlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kashfiyot',
            name='kategoriya',
            field=models.CharField(choices=[('ixtirolar', 'Ixtirolar'), ('tajribalar', 'Tajribalar'), ('sanalar', 'Sanalar'), ('olimlar', 'Olimlar'), ('rekordlar', 'Rekordlar')], default='ixtirolar', max_length=20, verbose_name='Kategoriya'),
        ),
    ]
