# Generated by Django 6.0.5 on 2026-05-17 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kashfiyotlar', '0002_alter_kashfiyot_kategoriya'),
    ]

    operations = [
        migrations.CreateModel(
            name='IxtirolarProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Ixtiro',
                'verbose_name_plural': 'Ixtirolar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('kashfiyotlar.kashfiyot',),
        ),
        migrations.CreateModel(
            name='OlimlarProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Olim',
                'verbose_name_plural': 'Olimlar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('kashfiyotlar.kashfiyot',),
        ),
        migrations.CreateModel(
            name='RekordlarProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Rekord',
                'verbose_name_plural': 'Rekordlar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('kashfiyotlar.kashfiyot',),
        ),
        migrations.CreateModel(
            name='SanalarProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Sana',
                'verbose_name_plural': 'Sanalar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('kashfiyotlar.kashfiyot',),
        ),
        migrations.CreateModel(
            name='TajribalarProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Tajriba',
                'verbose_name_plural': 'Tajribalar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('kashfiyotlar.kashfiyot',),
        ),
    ]
